# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  DISPLAY: ':0'

on:
  push:
    branches: [ issue/electron-builder-5907 ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: electronuserland/builder:wine-chrome

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          npm-version: 7
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-mocha --verbose
